flake: remove davhau's key due to change
```
error: NAR hash mismatch in input 'https://github.com/davhau.keys?narHash=sha256-0fd0gyrCTIDOPdmbPIKj7CD6696tiEumLZPoXqDd8dc=' (/nix/store/smzcyq8y5j921qap040zgayc6lznizz4-source), expected 'sha256-0fd0gyrCTIDOPdmbPIKj7CD6696tiEumLZPoXqDd8dc=', got 'sha256-R2zd7Y9035/Vgctl08KiQWYTvH4Pz9BwQlkqrAVTUhk='
```